#!/bin/sh

jupyter nbextension install --py widgetsnbextension --user
jupyter nbextension enable --py --sys-prefix ipyleaflet
jupyter nbextension enable --py gmaps
jupyter nbextension enable --py widgetsnbextension
